sudo: required
services:
  - docker

before_install:
  - docker build -t nekosakanakaeru/complex -f ./client/Dockerfile.dev ./client

scripts:
  - docker run -e CI=true nekosakanakaeru/complex npm test

after_success:
  - docker build nekosakanakaeru/complex-client ./client
  - docker build nekosakanakaeru/complex-nginx ./nginx
  - docker build nekosakanakaeru/complex-server ./server
  - docker build nekosakanakaeru/complex-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # push to docker hub
  - docker push nekosakanakaeru/complex-client
  - docker push nekosakanakaeru/complex-nginx
  - docker push nekosakanakaeru/complex-server
  - docker push nekosakanakaeru/complex-worker
